%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-plansys2-support-py
Version:        3.0.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS plansys2_support_py package

License:        Apache License, Version 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-lifecycle-msgs
Requires:       ros-kilted-plansys2-msgs
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-lifecycle-msgs
BuildRequires:  ros-kilted-plansys2-msgs
BuildRequires:  ros-kilted-rclpy
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-ament-copyright
BuildRequires:  ros-kilted-ament-flake8
BuildRequires:  ros-kilted-ament-pep257
%endif

%description
This package contains modules for developing PlanSys components in Python

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Dec 16 2025 Francisco Martin Rico <fmrico@gmail.com> - 3.0.2-1
- Autogenerated by Bloom

* Sun Jun 22 2025 Francisco Martin Rico <fmrico@gmail.com> - 3.0.1-1
- Autogenerated by Bloom

