name: rolling

on:
  pull_request:
    branches:
      - rolling
  push:
    branches:
      - rolling
  schedule:
      - cron: '0 0 * * 6'     
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Install popf deps
        run: sudo apt-get install libfl-dev
      - uses: actions/checkout@v2
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: rolling
      - name: Install BT.CPP v4 and test_msgs (provisional Fix)
        run: sudo apt-get install ros-rolling-behaviortree-cpp ros-rolling-test-msgs
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          package-name: plansys2_bringup plansys2_bt_actions plansys2_domain_expert plansys2_executor plansys2_lifecycle_manager plansys2_msgs plansys2_pddl_parser plansys2_planner plansys2_popf_plan_solver plansys2_problem_expert plansys2_terminal plansys2_tests plansys2_tools
          target-ros2-distro: rolling
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/dependency_repos.repos
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          fail_ci_if_error: false
